language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest test/test.py

deploy:
  - provider: heroku
    api_key: 
      secure: $HEROKU_API_KEY
app: ai-nad-api